// ACTION COUNTRIES

export const GET_COUNTRIES = 'GET_COUNTRIES'
export const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT';
export const ORDER_COUNTRIES_ALF = 'ORDER_COUNTRIES_ALF';
export const ORDER_COUNTRIES_POP = 'ORDER_COUNTRIES_POP';




// ACTION ACTIVITIES
