// ACTION COUNTRIES

export const GET_COUNTRIES = 'GET_COUNTRIES'
export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';
export const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT';
export const ORDER_COUNTRIES_ALF = 'ORDER_COUNTRIES_ALF';
export const ORDER_COUNTRIES_POP = 'ORDER_COUNTRIES_POP';
export const GET_COUNTRY_BY_NAME = 'GET_COUNTRY_BY_NAME';
export const GET_COUNTRIES_QUERY = 'GET_COUNTRIES_QUERY';
export const SET_ORDER = 'SET_ORDER';






// ACTION ACTIVITIES
export const GET_ACTIVITIES ='GET_ACTIVITIES'
export const UPDATE_ACTIVITY ='UPDATE_ACTIVITY'
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY'
export const RESET_FORM = 'RESET_FORM';



//ACTION PAGINADO
export const SET_PAGE = 'SET_PAGE';
export const SET_COUNTRIES_PER_PAGE = 'SET_COUNTRIES_PER_PAGE';
